"""
AEGIS — AI Ethics & Governance Integrated System
# Copyright (c) 2026 Kem Ada. Licensed under the MIT License.
Model Card Generator

Generates standardised model cards for AI systems.
Author: Kem Ada | https://linkedin.com/in/kem-a-695462101
"""

from dataclasses import dataclass, field
from typing import List, Optional
from datetime import date


@dataclass
class ModelCard:
    # Basic Info
    model_name: str
    version: str
    description: str
    model_type: str
    developed_by: str
    release_date: str

    # Use Cases
    intended_uses: List[str]
    out_of_scope_uses: List[str]

    # Data
    training_data_description: str
    data_sources: List[str]

    # Performance
    performance_summary: str
    known_limitations: List[str]

    # Ethics & Risk
    ethical_considerations: List[str]
    bias_risks: List[str]
    human_oversight: str

    # Contact
    contact: str = ""


def generate_model_card(card: ModelCard) -> str:
    """Generates a formatted markdown model card."""

    intended = "\n".join(f"- {u}" for u in card.intended_uses)
    out_of_scope = "\n".join(f"- {u}" for u in card.out_of_scope_uses)
    data_sources = "\n".join(f"- {s}" for s in card.data_sources)
    limitations = "\n".join(f"- {l}" for l in card.known_limitations)
    ethical = "\n".join(f"- {e}" for e in card.ethical_considerations)
    bias = "\n".join(f"- {b}" for b in card.bias_risks)

    return f"""# Model Card: {card.model_name}

> Generated by AEGIS — AI Ethics & Governance Integrated System

---

## Model Details

| Field | Details |
|---|---|
| **Model Name** | {card.model_name} |
| **Version** | {card.version} |
| **Model Type** | {card.model_type} |
| **Developed By** | {card.developed_by} |
| **Release Date** | {card.release_date} |
| **Contact** | {card.contact} |

---

## Model Description

{card.description}

---

## Intended Use

### Primary Intended Uses
{intended}

### Out-of-Scope Uses
{out_of_scope}

---

## Training Data

**Description:** {card.training_data_description}

**Data Sources:**
{data_sources}

---

## Performance

{card.performance_summary}

### Known Limitations
{limitations}

---

## Ethical Considerations

{ethical}

---

## Bias and Fairness Risks

{bias}

---

## Human Oversight

{card.human_oversight}

---

*Model card generated on {date.today()} using [AEGIS](https://github.com/Kem-Ada/AEGIS) — Open Source AI Governance Framework*
"""


if __name__ == "__main__":
    # Example usage
    example_card = ModelCard(
        model_name="Customer Credit Scoring Model",
        version="v2.1",
        description="A machine learning model that predicts credit risk for retail banking customers based on financial history and behavioural data.",
        model_type="Gradient Boosted Decision Tree (XGBoost)",
        developed_by="Internal Data Science Team",
        release_date="2024-01-15",
        intended_uses=[
            "Assessing creditworthiness for personal loan applications",
            "Supporting underwriters in credit decisions",
            "Portfolio risk monitoring"
        ],
        out_of_scope_uses=[
            "Sole automated decision-making without human review",
            "Assessment of individuals outside the UK market",
            "Insurance or employment screening"
        ],
        training_data_description="Historical loan application data from 2018-2023, covering 500,000 anonymised customer records.",
        data_sources=[
            "Internal loan application database",
            "Credit bureau data (Experian)",
            "Open Banking transaction data"
        ],
        performance_summary="Model achieves 87% accuracy on held-out test set. AUC-ROC: 0.91. False positive rate: 8%. False negative rate: 12%.",
        known_limitations=[
            "Performance degrades for applicants with limited credit history",
            "May underperform for recent immigrants without UK financial history",
            "Not validated for business lending decisions"
        ],
        ethical_considerations=[
            "Model outputs must be reviewed by a qualified underwriter before any credit decision",
            "Customers have the right to request human review of any automated assessment",
            "Model complies with GDPR Article 22 requirements on automated decision-making"
        ],
        bias_risks=[
            "Potential geographic bias — model trained predominantly on urban customer data",
            "Age bias risk — limited training data for applicants under 21",
            "Regular bias audits conducted quarterly"
        ],
        human_oversight="All high-risk decisions (decline or high-interest offer) require mandatory human review. Customers may request human review of any decision under GDPR Article 22.",
        contact="ai-governance@company.com"
    )

    markdown = generate_model_card(example_card)
    print(markdown)

    # Save to file
    with open("example_model_card.md", "w") as f:
        f.write(markdown)
    print("\nModel card saved to example_model_card.md")
